import { Component, signal, OnDestroy, ChangeDetectorRef, inject } from '@angular/core';
import { bootstrapApplication } from '@angular/platform-browser';
import { FormsModule } from '@angular/forms';
@Component({selector:'app-root',standalone:true,imports:[FormsModule],template:`
<aside><div class="brand"><b>R</b> RagHub <small>DEMO</small></div><p class="nav-label">KNOWLEDGE STUDIO</p><a>Workspaces</a><div class="side-note">Your knowledge.<br>Answers with sources.<p>BM25 + document excerpts<br>No API key required</p></div></aside>
<main><header><span>Studio / Workspaces</span><span>{{email || 'Welcome'}} @if(token){<button (click)="logout()">Sign out</button>}</span></header>
@if(!token){<section class="login"><span class="eyebrow">WELCOME TO RAGHUB</span><h1>Turn your documents<br>into conversations.</h1><p>Create an account to build your first knowledge workspace.</p><div class="demo-box"><div class="demo-box-title">💡 Hướng dẫn nhanh cho bản Demo</div><ol><li>Chưa có tài khoản mặc định — bạn cần đăng ký tài khoản mới.</li><li>Bấm nút bên dưới để điền nhanh hoặc tự nhập email & mật khẩu (≥ 8 ký tự).</li><li>Bấm <b>"Create account"</b> trước để đăng ký, sau đó có thể <b>"Sign in"</b>.</li></ol><button type="button" class="demo-fill-btn" (click)="fillDemo()">⚡ Điền nhanh thông tin mẫu</button></div><form (ngSubmit)="auth(false)"><label>Email<input type="email" name="email" [(ngModel)]="email" required placeholder="you@company.com"></label><label>Password<input type="password" name="password" [(ngModel)]="password" minlength="8" required placeholder="At least 8 characters"></label><button class="primary" [disabled]="busy">Sign in</button><button type="button" (click)="auth(true)" [disabled]="busy">Create account</button></form></section>}
@else{<section><div class="heading"><div><span class="eyebrow">YOUR KNOWLEDGE, CONNECTED</span><h1>Knowledge workspaces</h1><p>Manage documents, explore answers and publish your assistant.</p></div><span class="pill">Demo mode</span></div><div class="row"><select [ngModel]="wid" (ngModelChange)="selectWorkspace($event)"><option value="">Select workspace</option>@for(w of workspaces();track w.id){<option [value]="w.id">{{w.name}}</option>}</select><input [(ngModel)]="workspaceName" placeholder="New workspace name"><button class="primary" (click)="createWorkspace()" [disabled]="busy || !workspaceName.trim()">+ Create workspace</button></div>
@if(wid){<div class="stats"><article><span>DOCUMENTS</span><strong>{{documents().length}}</strong></article><article><span>READY TO SEARCH</span><strong>{{readyCount()}}</strong></article><article><span>ASSISTANTS</span><strong>{{bots().length}}</strong></article></div><div class="grid"><div><article><h2>Source documents</h2><p>Text-based PDF, TXT or Markdown. Up to 5 MB.</p><label class="upload">+ Choose a document to upload<input type="file" accept=".pdf,.txt,.md" (change)="upload($event)" [disabled]="busy"></label>@for(d of documents();track d.id){<div class="document"><div><b>{{d.name}}</b><small>{{d.chunk_count}} chunks / {{d.status}}</small>@if(d.error){<small class="error">{{d.error}}</small>}</div><div><button (click)="reindex(d.id)" [disabled]="busy">Retry</button><button (click)="remove(d.id)" [disabled]="busy">Delete</button></div></div>}@empty{<div class="empty">Your knowledge starts here.<br>Upload the first document.</div>}</article>
<article><h2>Chatbots & embedding</h2><div class="row"><input [(ngModel)]="botName" placeholder="Assistant name"><button (click)="createBot()" [disabled]="busy || !botName.trim()">+ Create</button></div><label>Allowed origins, separated by commas<input [(ngModel)]="origins"></label>@for(b of bots();track b.id){<div class="document"><b>{{b.name}}</b><button (click)="publish(b.id)" [disabled]="busy">{{b.published ? 'Unpublish' : 'Publish'}}</button></div>@if(b.published){<pre>{{embed(b.id)}}</pre><button (click)="copy(b.id)">Copy embed code</button>}}</article></div>
<article class="chat"><div class="heading"><h2>Playground</h2><span class="pill">Sources included</span></div><select [(ngModel)]="bid"><option value="">Select assistant</option>@for(b of bots();track b.id){<option [value]="b.id">{{b.name}}</option>}</select><div class="messages">@for(m of messages();track $index){<div [class]="'message '+m.role">{{m.text}}</div>}@empty{<div class="empty"><h2>Ask your knowledge</h2>Answers are excerpts from this workspace.<br>Demo retrieval does not use an LLM.</div>}@for(c of citations();track c.chunk_id){<details><summary>{{c.source}} / page {{c.page}}</summary>{{c.text}}</details>}</div><form (ngSubmit)="chat()"><input name="question" [(ngModel)]="question" placeholder="Ask about your documents..." maxlength="2000"><button class="primary" [disabled]="streaming || !bid || !question.trim()">{{streaming?'Thinking...':'Send'}}</button>@if(streaming){<button type="button" (click)="controller?.abort()">Stop</button>}</form></article></div>}@else{<article class="empty">Create a workspace to upload documents and start exploring.</article>}</section>}
@if(error()){<div class="toast" role="alert" (click)="error.set('')">{{error()}} [close]</div>}<footer>RagHub / Demo foundation <span>FastAPI / Angular / SQLite</span></footer></main>`})
class App implements OnDestroy {
 cdr=inject(ChangeDetectorRef);
 token='';email='';password='';busy=false;streaming=false;wid='';bid='';workspaceName='';botName='Knowledge assistant';question='';origins='http://localhost:8080,http://localhost:8081,http://localhost:4200';
 workspaces=signal<any[]>([]);documents=signal<any[]>([]);bots=signal<any[]>([]);messages=signal<any[]>([]);citations=signal<any[]>([]);error=signal('');controller?:AbortController;
 timer=setInterval(()=>{if(this.token&&this.wid&&this.documents().some(d=>['QUEUED','PARSING','CHUNKING'].includes(d.status)))this.refresh().catch(e=>this.error.set(e.message));},1500);
 ngOnDestroy(){clearInterval(this.timer);this.controller?.abort();}
 fillDemo(){this.email='demo@raghub.internal';this.password='demo123456';}
 async api(path:string,method='GET',body?:any){let r:Response;try{r=await fetch('/api/v1'+path,{method,headers:{...(this.token?{Authorization:'Bearer '+this.token}:{}),...(body&&!(body instanceof FormData)?{'Content-Type':'application/json'}:{})},body:body instanceof FormData?body:body?JSON.stringify(body):undefined});}catch{throw Error('Không thể kết nối đến máy chủ backend (127.0.0.1:8000). Vui lòng kiểm tra backend đã được khởi động chưa.');}if(!r.ok){let msg=`Lỗi yêu cầu (${r.status})`;try{const d=await r.json();msg=d.error?.message||(typeof d.detail==='string'?d.detail:JSON.stringify(d.detail))||msg;}catch{if(r.status===502||r.status===504){msg='Proxy không thể kết nối tới Backend (127.0.0.1:8000). Vui lòng kiểm tra uvicorn/FastAPI đã chạy chưa.';}else if(r.statusText){msg=`${r.status}: ${r.statusText}`;}}throw Error(msg);}return r.status===204?null:r.json().catch(()=>null);}
 async run(fn:()=>Promise<void>){this.busy=true;this.error.set('');try{await fn();}catch(e:any){this.error.set(e.message);}finally{this.busy=false;this.cdr.markForCheck();}}
 auth(register:boolean){this.run(async()=>{const d=await this.api('/auth/'+(register?'register':'login'),'POST',{email:this.email,password:this.password});this.token=d.access_token;this.password='';this.workspaces.set(await this.api('/workspaces'));if(this.workspaces().length)await this.selectWorkspace(this.workspaces()[0].id);});}
 logout(){this.run(async()=>{await this.api('/auth/logout','POST');this.controller?.abort();this.token='';this.wid='';this.messages.set([]);});}
 createWorkspace(){this.run(async()=>{const w=await this.api('/workspaces','POST',{name:this.workspaceName});this.workspaceName='';this.workspaces.set(await this.api('/workspaces'));await this.selectWorkspace(w.id);});}
 async selectWorkspace(id:string){this.controller?.abort();this.wid=id;this.bid='';this.messages.set([]);this.citations.set([]);this.documents.set([]);this.bots.set([]);if(id)try{await this.refresh();}catch(e:any){this.error.set(e.message);}}
 async refresh(){const id=this.wid;const [docs,bots]=await Promise.all([this.api('/workspaces/'+id+'/documents'),this.api('/workspaces/'+id+'/chatbots')]);if(id!==this.wid)return;this.documents.set(docs.filter((d:any)=>d.status!=='DELETED'));this.bots.set(bots);if(!this.bid)this.bid=bots[0]?.id||'';}
 readyCount(){return this.documents().filter(d=>d.status==='READY').length;}
 upload(event:Event){const input=event.target as HTMLInputElement;const file=input.files?.[0];if(!file)return;this.run(async()=>{const data=new FormData();data.append('file',file);await this.api('/workspaces/'+this.wid+'/documents','POST',data);input.value='';await this.refresh();});}
 reindex(id:string){this.run(async()=>{await this.api('/documents/'+id+'/reindex','POST');await this.refresh();});}
 remove(id:string){this.run(async()=>{await this.api('/documents/'+id,'DELETE');await this.refresh();});}
 createBot(){this.run(async()=>{await this.api('/workspaces/'+this.wid+'/chatbots','POST',{name:this.botName,allowed_origins:this.origins.split(',').map(x=>x.trim()).filter(Boolean)});await this.refresh();});}
 publish(id:string){this.run(async()=>{await this.api('/chatbots/'+id+'/publish','POST');await this.refresh();});}
 embed(id:string){return '<script src="'+location.origin+'/widget/raghub.js" data-chatbot-key="'+id+'" defer><'+'/script>';}
 copy(id:string){this.run(async()=>{await navigator.clipboard.writeText(this.embed(id));});}
  async chat(){if(this.streaming||!this.question.trim()||!this.bid)return;const text=this.question;this.question='';this.messages.update(x=>[...x,{role:'user',text},{role:'assistant',text:''}]);this.citations.set([]);this.streaming=true;const controller=new AbortController();this.controller=controller;const wid=this.wid;try{const r=await fetch('/api/v1/chatbots/'+this.bid+'/test',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+this.token},body:JSON.stringify({message:text}),signal:controller.signal});if(!r.ok){let msg='Chat failed';try{const e=await r.json();msg=e.error?.message||msg;}catch{msg=r.statusText||('Lỗi '+r.status);}throw Error(msg);}const reader=r.body!.getReader();const decoder=new TextDecoder();let buffer='';while(true){const {value,done}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});let end;while((end=buffer.indexOf('\n\n'))>=0){const lines=buffer.slice(0,end).split('\n');buffer=buffer.slice(end+2);const type=lines[0].slice(7);const data=JSON.parse(lines[1].slice(6));if(wid!==this.wid)continue;if(type==='token')this.messages.update(x=>x.map((m,i)=>i===x.length-1?{...m,text:m.text+data}:m));if(type==='citations')this.citations.set(data);}}}catch(e:any){if(e.name!=='AbortError')this.error.set(e.message);}finally{this.streaming=false;this.cdr.markForCheck();}}

}
bootstrapApplication(App).catch(console.error);
