from typing import Protocol
from uuid import UUID

from app.core_domain.chatbots.models import ChatbotConfig, ChatbotRecord, CreateChatbotCommand
from app.core_domain.retrieval.models import RetrievalScope


class ChatbotReadPort(Protocol):
    async def get(self, organization_id: UUID, chatbot_id: UUID) -> ChatbotConfig: ...


class ChatbotRepositoryPort(Protocol):
    async def workspace_exists(self, scope: RetrievalScope) -> bool: ...
    async def list(self, scope: RetrievalScope) -> list[ChatbotRecord]: ...
    async def get(self, organization_id: UUID, chatbot_id: UUID) -> ChatbotRecord | None: ...
    async def create(self, command: CreateChatbotCommand) -> ChatbotRecord: ...
    async def save(self, record: ChatbotRecord) -> ChatbotRecord: ...
    async def delete(self, record: ChatbotRecord) -> None: ...
