from typing import Protocol, runtime_checkable


@runtime_checkable
class ObjectStoragePort(Protocol):
    async def put(self, key: str, content: bytes, content_type: str) -> None: ...
    async def get(self, key: str) -> bytes: ...
    async def remove(self, key: str) -> None: ...
