from typing import Protocol, runtime_checkable


@runtime_checkable
class ObjectStoragePort(Protocol):
    def put(self, key: str, content: bytes, content_type: str) -> None: ...
    def get(self, key: str) -> bytes: ...
    def remove(self, key: str) -> None: ...
