from typing import Protocol
from uuid import UUID

from raghub_core.domain.ingestion.errors import IngestionError
from raghub_core.domain.ingestion.models import IngestionAttempt, IngestionStage


class IngestionRepositoryPort(Protocol):
    async def load(self, version_id: UUID) -> IngestionAttempt | None: ...
    async def begin(self, version_id: UUID) -> None: ...
    async def set_stage(self, version_id: UUID, stage: IngestionStage, progress: int) -> None: ...
    async def expose_version(self, version_id: UUID) -> None: ...
    async def complete(self, version_id: UUID) -> None: ...
    async def record_failure(
        self, version_id: UUID, error: IngestionError, *, failed: bool
    ) -> None: ...
