from typing import Protocol
from uuid import UUID

from raghub_core.domain.ingestion.models import IngestionDocument
from raghub_core.domain.ingestion.reindex import ReindexTarget


class ReindexRepositoryPort(Protocol):
    async def load(self, job_id: UUID) -> ReindexTarget | None: ...
    async def mark(self, job_id: UUID, status: str) -> None: ...
    async def latest_documents(self, target: ReindexTarget) -> list[IngestionDocument]: ...
    async def reset_progress(self, job_id: UUID, total: int) -> None: ...
    async def processed(self, job_id: UUID) -> None: ...
    async def activate(self, target: ReindexTarget) -> bool: ...
    async def fail(self, job_id: UUID, exc: Exception) -> None: ...
    async def rollback(self) -> None: ...
