from enum import StrEnum


class ProviderType(StrEnum):
    OPENAI_COMPATIBLE = "OPENAI_COMPATIBLE"
    GOOGLE_GEMINI = "GOOGLE_GEMINI"
    LOCAL_SENTENCE_TRANSFORMER = "LOCAL_SENTENCE_TRANSFORMER"
    OLLAMA = "OLLAMA"


class ProviderCapability(StrEnum):
    EMBEDDING = "EMBEDDING"
    CHAT = "CHAT"


class IndexVersionStatus(StrEnum):
    BUILDING = "BUILDING"
    ACTIVE = "ACTIVE"
    FAILED = "FAILED"
    RETIRED = "RETIRED"


class ReindexJobStatus(StrEnum):
    QUEUED = "QUEUED"
    QUEUE_FAILED = "QUEUE_FAILED"
    RUNNING = "RUNNING"
    VALIDATING = "VALIDATING"
    SWITCHING = "SWITCHING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    SUPERSEDED = "SUPERSEDED"
