from enum import StrEnum


class ProviderType(StrEnum):
    OPENAI_COMPATIBLE = "OPENAI_COMPATIBLE"
    GOOGLE_GEMINI = "GOOGLE_GEMINI"
    LOCAL_TOKEN_HASH = "LOCAL_TOKEN_HASH"
    LOCAL_SENTENCE_TRANSFORMER = "LOCAL_SENTENCE_TRANSFORMER"
    OLLAMA = "OLLAMA"
    VOYAGE = "VOYAGE"
    HUGGINGFACE_INFERENCE = "HUGGINGFACE_INFERENCE"
    CLOUDFLARE_WORKERS_AI = "CLOUDFLARE_WORKERS_AI"


class ProviderCapability(StrEnum):
    EMBEDDING = "EMBEDDING"
    CHAT = "CHAT"
    RERANK = "RERANK"


class IndexVersionStatus(StrEnum):
    BUILDING = "BUILDING"
    ACTIVE = "ACTIVE"
    FAILED = "FAILED"
    RETIRED = "RETIRED"


class ReindexJobStatus(StrEnum):
    QUEUED = "QUEUED"
    QUEUE_FAILED = "QUEUE_FAILED"
    RUNNING = "RUNNING"
    VALIDATING = "VALIDATING"
    SWITCHING = "SWITCHING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    SUPERSEDED = "SUPERSEDED"
